version: '3'

services:
  ptubus_server:
    env_file:
      - ./.env.dev
    container_name: ptubus_server
    build:
      context: .
    ports:
      - 7777:7777
    volumes:
      - .:/code
    environment:
      TZ: "Asia/Seoul"
    command:
        python manage.py runserver 0.0.0.0:7777
