# Generated by Django 3.1.4 on 2021-01-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolBusTimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_station_name', models.CharField(max_length=100)),
                ('start_station_id', models.CharField(max_length=100)),
                ('end_station_name', models.CharField(max_length=100)),
                ('end_station_id', models.CharField(max_length=100)),
                ('schedule', models.CharField(max_length=100)),
                ('up_down_type_code', models.CharField(max_length=20)),
            ],
        ),
    ]
