# Generated by Django 3.1.4 on 2021-03-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptu_school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolbustimetable',
            name='key',
            field=models.IntegerField(default=None, editable=False),
        ),
    ]
