# Generated by Django 3.1.4 on 2021-01-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubwayLine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lineName', models.CharField(max_length=100)),
                ('lineCode', models.CharField(max_length=100)),
                ('lineColorCode', models.CharField(max_length=100)),
                ('lineSaidName', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubwayStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stationName', models.CharField(max_length=100)),
                ('stationCode', models.CharField(max_length=100)),
                ('lineCode', models.CharField(max_length=100)),
                ('railLineCode', models.CharField(max_length=100)),
            ],
        ),
    ]
