# Generated by Django 3.1.4 on 2021-01-16 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusTerminal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_station_name', models.CharField(max_length=100)),
                ('start_station_id', models.CharField(max_length=100)),
                ('end_station_name', models.CharField(max_length=100)),
                ('end_station_id', models.CharField(max_length=100)),
                ('is_express', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='BusTimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('waste_time', models.CharField(max_length=100)),
                ('normal_fare', models.CharField(max_length=100)),
                ('special_fare', models.CharField(max_length=100)),
                ('night_fare', models.CharField(max_length=100)),
                ('schedule', models.CharField(max_length=100)),
                ('night_schedule', models.CharField(max_length=100)),
                ('bus_terminal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_bus_timetable', to='ptu_bus.busterminal')),
            ],
        ),
    ]
