# Generated by Django 3.1.4 on 2021-03-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptu_bus', '0002_auto_20210204_0259'),
    ]

    operations = [
        migrations.AddField(
            model_name='busterminal',
            name='key',
            field=models.IntegerField(default=None, editable=False),
        ),
        migrations.AddField(
            model_name='bustimetable',
            name='key',
            field=models.IntegerField(default=None, editable=False),
        ),
    ]
