# Generated by Django 3.1.4 on 2021-01-16 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TrainStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_station_name', models.CharField(max_length=100)),
                ('start_station_id', models.CharField(max_length=100)),
                ('end_station_name', models.CharField(max_length=100)),
                ('end_station_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrainTimeTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rail_name', models.CharField(max_length=100)),
                ('train_class', models.CharField(max_length=100)),
                ('departure_time', models.CharField(max_length=100)),
                ('schedule', models.CharField(max_length=100)),
                ('waste_time', models.CharField(max_length=100)),
                ('daily_type_code', models.CharField(max_length=100)),
                ('train_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_train_timetable', to='ptu_train.trainstation')),
            ],
        ),
    ]
