# Generated by Django 3.1.4 on 2021-02-12 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptu_train', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TrainStation',
            new_name='TrainTerminal',
        ),
        migrations.RenameField(
            model_name='trainterminal',
            old_name='end_station_id',
            new_name='end_terminal_id',
        ),
        migrations.RenameField(
            model_name='trainterminal',
            old_name='end_station_name',
            new_name='end_terminal_name',
        ),
        migrations.RenameField(
            model_name='trainterminal',
            old_name='start_station_id',
            new_name='start_terminal_id',
        ),
        migrations.RenameField(
            model_name='trainterminal',
            old_name='start_station_name',
            new_name='start_terminal_name',
        ),
        migrations.RenameField(
            model_name='traintimetable',
            old_name='train_station',
            new_name='train_terminal',
        ),
    ]
