# Generated by Django 3.1.4 on 2021-03-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptu_train', '0002_auto_20210213_0219'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainterminal',
            name='key',
            field=models.IntegerField(default=None, editable=False),
        ),
        migrations.AddField(
            model_name='traintimetable',
            name='key',
            field=models.IntegerField(default=None, editable=False),
        ),
    ]
